function [fitresult, gof] = crateFittingModelAngleRatioRelashionshipt(alphaDeg, flankCrop)
%CREATEFIT(ALPHADEG,FLANKCROP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : alphaDeg
%      Y Output: flankCrop
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Oct-2014 13:12:33


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( alphaDeg, flankCrop );

% Set up fittype and options.
ft = fittype( 'sin2' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [0.650343387922383 0.0174539308496984 0.174432962597827 0.470401277331754 0.0349078616993969 1.58694369195864];
opts.Upper = [Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'flankCrop vs. alphaDeg', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'alphaDeg' );
ylabel( 'flankCrop' );
grid on


