function [fitresult, gof] = createFitPolyFit(alphaDeg, flankCrop)
%CREATEFIT(ALPHADEG,FLANKCROP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : alphaDeg
%      Y Output: flankCrop
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Oct-2014 13:24:22


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( alphaDeg, flankCrop );

% Set up fittype and options.
ft = fittype( 'poly4' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf -Inf -Inf];
opts.Robust = 'LAR';
opts.Upper = [Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'flankCrop vs. alphaDeg', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'alphaDeg' );
ylabel( 'flankCrop' );
grid on


