function [fitresult, gof] = createFitPolyFitAngleIntensity(alphaDeg, flankCrop)
%CREATEFIT(ALPHADEG,FLANKCROP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : alphaDeg
%      Y Output: flankCrop
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Oct-2014 13:24:22


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( alphaDeg, flankCrop );

% Set up fittype and options.
ft = fittype( 'poly4' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf -Inf -Inf];
opts.Robust = 'LAR';
opts.Upper = [Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = scatter( fitresult, xData, yData,'.k'); hold on
set(h, 'MarkerFaceColor', 'c')
alpha(h,0.1);

legend( h, 'Normalized intensity', 'Fit', 'Location', 'NorthEast' );
% Label axes
xlabel( 'Alpha (degree)' );
ylabel( 'Normalized intensity (a.u.)' );
grid on


